### ISSUE TITLE
some issue in Contract

### ISSUE THREAD

**Issue by devjangir** [argentlabs/application#3]
I think there are some issue in contract, as the apply function always call "this.sendTransaction.apply" function so always getting "Invalid Address"

Uncaught Error: invalid address
    at u (web3.min.js:1)
    at inputTransactionFormatter (web3.min.js:1)
    at web3.min.js:1
    at Array.map (<anonymous>)
    at i.formatInput (web3.min.js:1)
    at i.toPayload (web3.min.js:1)
    at r.e [as sendTransaction] (web3.min.js:1)
    at c.sendTransaction (web3.min.js:1)
    at c.execute (web3.min.js:1)
    at Index.html:56

**Comment by cmaliwal** [comment]
Facing the same issue 



```
> var abi = [{"constant": false,"inputs": [{"name": "hash","type": "bytes32"}],"name": "apply","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function"},{"constant": true,"inputs": [{"name": "email","type": "string"}],"name": "getApplicationID","outputs": [{"name": "","type": "uint256"}],"payable": false,"stateMutability": "view","type": "function"}];
undefined
> var myContract = web3.eth.contract(abi);
undefined
> var myContractInstance = myContract.at("0xcbbfbafedb0eb83016d2a96a4e80d30b20fa3e30");
undefined
> var result = myContractInstance.apply("0x736cd237bc901dfb88df43524aee1e32e496ab266d19afda9726e5d1194f3cfb");
Error: invalid address
    at web3.js:3930:15
    at web3.js:3756:20
    at web3.js:5025:28
    at map (<native code>)
    at web3.js:5024:12
    at web3.js:5050:18
    at web3.js:5075:23
    at web3.js:4137:16
    at apply (<native code>)
    at web3.js:4223:16
```

**Comment by alexandrucaraus** [comment]
I get the same, the contract is invalid.

**Comment by VassiliKurman** [comment]
For contract ABI got message: {"status":"0","message":"NOTOK","result":"Contract source code not verified"}

**Comment by minuscorp** [comment]
+1 contract not valid
